# _config.yml 0.0.10                   UTF-8                     dh:2017-12-12
#
#                       SPANNER WINGNUT'S MUDDLEWARE LAB
#                       ================================
#
#                        AUTHORING FOLDER CUSTOMISATION
#
#               source: nfoCentrale/spanner/_config.yml
#               mirror: http://orcmid.com/BlunderDome/wingnut/about/
#              archive: $/nfoCentrale/spanner/_config.yml
#
#                         HEXO AUTHORING CONFIGURATION
#                         ----------------------------

# Hexo Configuration
##   Docs: https://hexo.io/docs/setup.html                  # 0.0.5 
##         https://hexo.io/docs/configuration.html          
## Source: https://github.com/hexojs/hexo/
##   More: https://github.com/hexojs/awesome-hexo           # 0.0.5
##         http://jrocket.co.uk/hexo (by John Stevenson)    # 0.0.6

# Site
title: "Spanner Wingnut's Muddleware Lab"                   # 0.0.1
subtitle: experimental web-site and blog-generation lab     # 0.0.7                                           
description:                                       
author: Dennis E. Hamilton                                  # 0.0.1
language: en                                                # 0.0.1
timezone: UTC                                               # 0.0.1

# URL
## If your site is put in a subdirectory, set url as 
## 'http://yoursite.com/child' and root as '/child/'
url: http://orcmid.com/BlunderDome/wingnut                  # 0.0.1
root: /BlunderDome/wingnut/                                 # 0.0.3
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: hexo-tags                                          # 0.0.7
archive_dir: hexo-archives                                  # 0.0.7
category_dir: hexo-categories                               # 0.0.7
code_dir: hexo-downloads/code                               # 0.0.7
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: false # Open external links in new tab       # 0.0.2
filename_case: 0
render_drafts: false
post_asset_folder: true                                     # 0.0.2
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
    
# RSS Feed                                                 # 0.0.10
feed:
  type: atom
  path: /hexo-atom.xml
  limit: 0
  hub:
  content: true
    
# Disqus (hat tip to John Stevenson)                        # 0.0.6
disqus_shortname: wingnut-1
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 0                                               # 0.0.7
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0    # seems to be second place for this         # 0.0.8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

theme: landscape                                            # 0.0.9
## landscape theme installed by default with initial Hexo   # 0.0.5
##    configuration, hexjos/hexo-theme-landscape, at  
##    <https://github.com/hexojs/hexo-theme-landscape>
##    <http://jr0cket.co.uk/hexo/hexo-theme-simple-changes.html> 
##    renamed to wingnut to reflect the customization       # 0.0.8

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
    
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# TODO
#  * See how to get one full page on the front page, if that makes any
#    useful difference.  It may be simple enough to just leave things alone.
#  * Find out how the setting of relative links matters.
#  * Find out how to deal with the category_map setting
#  * Find out how to deal with the tag_map setting
#
# 0.0.10 2017-12-12-14:46 Enable RSS Feed
# 0.0.9 2017-12-12-07:27 Switch theme name back to landscape because there 
#       might be different themes at other times, and using wingnut is too
#       generic.  And there is already much material that rfers to the theme
#       as landscape.
# 0.0.8 2017-12-11-19:20 Switch theme name to wingnut reflecting the 
#       customization.  The A2wingnut.ctl will not need to be changed because
#       it works from spanner/public.  Set per_page 0 in both places.
# 0.0.7 2017-11-28-17:26 Make the additional subordinate folders all hexo-
#       prefixed and tweak the subtitle.  Manage TODOs.
# 0.0.6 2017-11-11-16:30 Touch-up with additional links to confirmations.
#       Include DisQus short-name and attempt nested subfolders with about/.
# 0.0.5 2017-11-11-15:08 Linking more documentation and source files for the
#       key dependencies.
# 0.0.4 2017-11-04-11:14 Reflect renaming of folder to nfoCentrale/spanner/
# 0.0.3 2017-11-04-08:07 Correct to _config.yml in top-line, add TODOs.
#       Change URL root: to exactly match the specified pattern.
# 0.0.2 2017-10-29-09:50 Adjust writing to use assets folders and not open
#       links in new windows/tabs.
# 0.0.1 2017-10-25-17:46 Provide Spanner Wingnut Title and URL information.
# 0.0.0 2017-10-25-10:09 Default setup after Hexo initialization of the
#       authoring folder.  No modifications other than addition of 
#       identifying comments and version history.
#
#                   **** end of _config.yml ****    
